"""
Single source of truth for all strategy parameters, assembled from
config.py. Every script that runs a strategy (run_backtest.py,
walk_forward.py, run_holdout_check.py) imports BASE_PARAMS from here
instead of each maintaining its own copy.

This is also the natural place a future UI's "adjust parameters or use
defaults" screen would read defaults from -- one flat dict of every
adjustable knob across every strategy.
"""
from config import (
    ATR_PERIOD,
    RSI_OVERSOLD, RSI_OVERBOUGHT, SR_PROXIMITY_PCT, VOLUME_MULTIPLIER,
    VOLATILITY_THRESHOLD_PCT, RISK_REWARD_RATIO, BACKTEST_FEE_PCT,
    BACKTEST_SLIPPAGE_PCT, BACKTEST_MAX_HOLD_BARS, BREAKOUT_RISK_REWARD_RATIO,
    TREND_EMA_FAST, TREND_EMA_SLOW, TREND_RISK_REWARD_RATIO,
    BREAKOUT_LOOKBACK_BARS, BREAKOUT_MIN_MARGIN_PCT,
    FIB_RISK_REWARD_RATIO,
    SD_BASE_MAX_ATR_MULT, SD_DISPLACEMENT_ATR_MULT, SD_MAX_ZONE_AGE_BARS, SD_RISK_REWARD_RATIO,
    SMC_WICK_MIN_ATR_MULT, SMC_RISK_REWARD_RATIO,
    PIVOT_LOOKBACK_BARS, DOUBLE_PATTERN_TOLERANCE_PCT, DOUBLE_PATTERN_MAX_BARS_APART,
    DOUBLE_PATTERN_RISK_REWARD_RATIO,
    USE_TRAILING_STOP, TRAIL_ACTIVATION_R, TRAIL_DISTANCE_ATR_MULT,
    FUNDING_EXTREME_POSITIVE_PCT, FUNDING_EXTREME_NEGATIVE_PCT, FUNDING_RISK_REWARD_RATIO,
    MIN_CONFLUENCE_SCORE, CONFLUENCE_WEIGHT_RSI, CONFLUENCE_WEIGHT_TREND, CONFLUENCE_WEIGHT_MACD,
    CONFLUENCE_WEIGHT_VOLUME, CONFLUENCE_WEIGHT_SR, CONFLUENCE_WEIGHT_FUNDING, CONFLUENCE_RISK_REWARD_RATIO,
    PAIRS_BASE_SYMBOL, PAIRS_ZSCORE_LOOKBACK_BARS, PAIRS_ZSCORE_ENTRY_THRESHOLD, PAIRS_RISK_REWARD_RATIO,
    VOL_BREAKOUT_LOOKBACK_BARS, VOL_BREAKOUT_ATR_BASELINE_BARS, VOL_BREAKOUT_ATR_EXPANSION_MULT,
    VOL_BREAKOUT_MIN_MARGIN_PCT, VOL_BREAKOUT_EMA_PERIOD, VOL_BREAKOUT_RISK_REWARD_RATIO,
)

BASE_PARAMS = {
    "ATR_PERIOD": ATR_PERIOD,
    "RSI_OVERSOLD": RSI_OVERSOLD,
    "RSI_OVERBOUGHT": RSI_OVERBOUGHT,
    "SR_PROXIMITY_PCT": SR_PROXIMITY_PCT,
    "VOLUME_MULTIPLIER": VOLUME_MULTIPLIER,
    "VOLATILITY_THRESHOLD_PCT": VOLATILITY_THRESHOLD_PCT,
    "RISK_REWARD_RATIO": RISK_REWARD_RATIO,
    "BACKTEST_FEE_PCT": BACKTEST_FEE_PCT,
    "BACKTEST_SLIPPAGE_PCT": BACKTEST_SLIPPAGE_PCT,
    "BACKTEST_MAX_HOLD_BARS": BACKTEST_MAX_HOLD_BARS,
    "BREAKOUT_RISK_REWARD_RATIO": BREAKOUT_RISK_REWARD_RATIO,
    "TREND_EMA_FAST": TREND_EMA_FAST,
    "TREND_EMA_SLOW": TREND_EMA_SLOW,
    "TREND_RISK_REWARD_RATIO": TREND_RISK_REWARD_RATIO,
    "BREAKOUT_LOOKBACK_BARS": BREAKOUT_LOOKBACK_BARS,
    "BREAKOUT_MIN_MARGIN_PCT": BREAKOUT_MIN_MARGIN_PCT,
    "FIB_RISK_REWARD_RATIO": FIB_RISK_REWARD_RATIO,
    "SD_BASE_MAX_ATR_MULT": SD_BASE_MAX_ATR_MULT,
    "SD_DISPLACEMENT_ATR_MULT": SD_DISPLACEMENT_ATR_MULT,
    "SD_MAX_ZONE_AGE_BARS": SD_MAX_ZONE_AGE_BARS,
    "SD_RISK_REWARD_RATIO": SD_RISK_REWARD_RATIO,
    "SMC_WICK_MIN_ATR_MULT": SMC_WICK_MIN_ATR_MULT,
    "SMC_RISK_REWARD_RATIO": SMC_RISK_REWARD_RATIO,
    "PIVOT_LOOKBACK_BARS": PIVOT_LOOKBACK_BARS,
    "DOUBLE_PATTERN_TOLERANCE_PCT": DOUBLE_PATTERN_TOLERANCE_PCT,
    "DOUBLE_PATTERN_MAX_BARS_APART": DOUBLE_PATTERN_MAX_BARS_APART,
    "DOUBLE_PATTERN_RISK_REWARD_RATIO": DOUBLE_PATTERN_RISK_REWARD_RATIO,
    "USE_TRAILING_STOP": USE_TRAILING_STOP,
    "TRAIL_ACTIVATION_R": TRAIL_ACTIVATION_R,
    "TRAIL_DISTANCE_ATR_MULT": TRAIL_DISTANCE_ATR_MULT,
    "FUNDING_EXTREME_POSITIVE_PCT": FUNDING_EXTREME_POSITIVE_PCT,
    "FUNDING_EXTREME_NEGATIVE_PCT": FUNDING_EXTREME_NEGATIVE_PCT,
    "FUNDING_RISK_REWARD_RATIO": FUNDING_RISK_REWARD_RATIO,
    "MIN_CONFLUENCE_SCORE": MIN_CONFLUENCE_SCORE,
    "CONFLUENCE_WEIGHT_RSI": CONFLUENCE_WEIGHT_RSI,
    "CONFLUENCE_WEIGHT_TREND": CONFLUENCE_WEIGHT_TREND,
    "CONFLUENCE_WEIGHT_MACD": CONFLUENCE_WEIGHT_MACD,
    "CONFLUENCE_WEIGHT_VOLUME": CONFLUENCE_WEIGHT_VOLUME,
    "CONFLUENCE_WEIGHT_SR": CONFLUENCE_WEIGHT_SR,
    "CONFLUENCE_WEIGHT_FUNDING": CONFLUENCE_WEIGHT_FUNDING,
    "CONFLUENCE_RISK_REWARD_RATIO": CONFLUENCE_RISK_REWARD_RATIO,
    "PAIRS_BASE_SYMBOL": PAIRS_BASE_SYMBOL,
    "PAIRS_ZSCORE_LOOKBACK_BARS": PAIRS_ZSCORE_LOOKBACK_BARS,
    "PAIRS_ZSCORE_ENTRY_THRESHOLD": PAIRS_ZSCORE_ENTRY_THRESHOLD,
    "PAIRS_RISK_REWARD_RATIO": PAIRS_RISK_REWARD_RATIO,
    "VOL_BREAKOUT_LOOKBACK_BARS": VOL_BREAKOUT_LOOKBACK_BARS,
    "VOL_BREAKOUT_ATR_BASELINE_BARS": VOL_BREAKOUT_ATR_BASELINE_BARS,
    "VOL_BREAKOUT_ATR_EXPANSION_MULT": VOL_BREAKOUT_ATR_EXPANSION_MULT,
    "VOL_BREAKOUT_MIN_MARGIN_PCT": VOL_BREAKOUT_MIN_MARGIN_PCT,
    "VOL_BREAKOUT_EMA_PERIOD": VOL_BREAKOUT_EMA_PERIOD,
    "VOL_BREAKOUT_RISK_REWARD_RATIO": VOL_BREAKOUT_RISK_REWARD_RATIO,
}


def parse_overrides(override_strings):
    """
    override_strings: list of 'KEY=VALUE' strings, typically from a
    repeatable --override CLI argument. Casts VALUE to match the type of
    the existing BASE_PARAMS[KEY] (bool/int/float) when the key is known;
    otherwise infers a sensible type. This is what lets a parameter
    combination found by backtest/optimize.py actually be checked against
    holdout via run_holdout_check.py, without editing config.py.
    """
    overrides = {}
    for item in override_strings or []:
        if "=" not in item:
            raise ValueError(f"--override must be KEY=VALUE, got: {item!r}")
        key, raw_value = item.split("=", 1)
        key, raw_value = key.strip(), raw_value.strip()

        if key in BASE_PARAMS and isinstance(BASE_PARAMS[key], bool):
            value = raw_value.lower() in ("1", "true", "yes")
        elif key in BASE_PARAMS and isinstance(BASE_PARAMS[key], int):
            value = int(raw_value)
        elif key in BASE_PARAMS and isinstance(BASE_PARAMS[key], float):
            value = float(raw_value)
        else:
            try:
                value = int(raw_value)
            except ValueError:
                try:
                    value = float(raw_value)
                except ValueError:
                    value = raw_value.lower() == "true" if raw_value.lower() in ("true", "false") else raw_value
        overrides[key] = value
    return overrides
